name: Generate Core Pools JSON

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  refresh_books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Update Files
        id: update
        run: |
          pip3 install -r bal_addresses/requirements.txt
          python3 gen_core_pools.py
          git add -A

      - name: pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Scheduled updates to Core Pools list"
          title: "Scheduled updates to Core Pools list"
          branch: "gha-corepools"
          reviewers: "gosuto-inzasheru"
          labels: "Core Pools"
