name: Generate Addressbooks

on:
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:

jobs:
  refersh_books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Update Files
        id: update
        run: |
          git clone https://github.com/balancer/balancer-deployments.git
          export DEPLOYMENTS_REPO_ROOT_URL=`pwd`/balancer-deployments
          pip3 install -r bal_addresses/requirements.txt
          python3 gen_pools_and_gauges.py
          python3 transform-deployments.py
          python3 gen_addresses.py
          rm -rf balancer-deployments
          git add -A

      - name: pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Scheduled update from changes to monorepo"
          title: "Scheduled update from changes to monorepo"
          branch: "gha-addressbook"
          reviewers: "Tritum-VLK"
          assignees: "Tritum-VLK"
          labels: "Automatic"
