name: Generate Addressbooks

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  refersh_books:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Update Files
      id: update
      run: |
        git clone https://github.com/balancer/balancer-v2-monorepo.git
        export MONOREPO_ROOT=$pwd/balancer-v2-monorepo
        pip3 install -r requirements.txt
        python3 transform-deployments.py
        python3 gen_addresses.py
        rm -rf balancer-v2-monorepo

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: "Scheduled update from changes to monorepo"
        pr_reviewer: "Tritum-VLK"
        pr_assignee: "Tritum-VLK"
        pr_label: "Automatic"
        pr_allow_empty: false
